name: PlantUML cli
description: generate svg's from plantuml
inputs:
  version:
    description: PlantUML version
    required: false
  output-format:
    description: Output format, -t, e.g. svg, png, defaults to svg
    required: true
    default: svg
  output:
    description: PlantUML output directory, -o
    required: false
  include:
    description: PlantUML files to include with -I
    required: false
  files:
    description: PlantUML input files, can be a pattern, directory, or list, defaults to **/*.puml
    required: true
    default: '**/*.puml'
  args:
    description: additional PlantUML arguments e.g. -config foo.puml -Itheme.puml
    required: false
  directories:
    description: output directories
    required: false
runs:
  using: composite
  steps:
    - run: mkdir -p ${{ inputs.directories }}
      shell: bash
    - id: jar
      shell: bash
      run: |
        echo "::group::jar"
        OUT=`echo ${{ inputs.version }} | awk '{ print (match( $0, /^([[:digit:].]+)/, capture)) ? "plantuml." capture[1] ".jar" : "plantuml.jar" }'`
        echo "::set-output name=filename::$OUT"
        echo "::endgroup::"
    - run: |
        echo "::group::download"
        URL=https://downloads.sourceforge.net/project/plantuml
        wget --timestamping --no-verbose $URL/${{ steps.jar.outputs.filename }}
        echo "::endgroup::"
      shell: bash
    - run: |
        echo "::group::version"
        java -jar plantuml.jar -version
        echo "::endgroup::"
      shell: bash
    - run: |
        echo "::group::plantuml"
        java -jar ${{steps.jar.outputs.filename }} -verbose \
          -t${{ inputs.output-format }} \
          -output ${{ inputs.output }} \
          -I ${{ inputs.include }} \
          ${{ inputs.args }} \
          ${{ inputs.files }}
        echo "::endgroup::"
      shell: bash
    - run: ls -1aR docs/domain-model
      shell: bash
    - run: git status
      shell: bash
