name: PlantUML
on:
  push:
    tags-ignore:
      - '**'
    paths:
      - '**.puml'
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: get remote branch name
        id: branch
        run: |
          BRANCH=$(echo $GITHUB_REF | cut --delimiter / --fields '3-')
          echo "::set-output name=name::$BRANCH"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Generate SVG images for PlantUML diagrams'
          file_pattern: '*.svg'
          branch: ${{ steps.branch.outputs.name }}
