name: PlantUML
on:
  push:
    paths:
    - '**.puml'
    tags-ignore:
    - '**'
    branches-ignore:
    - master
    - maint
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 2
    - uses: ts-graphviz/setup-graphviz@v1
    - uses: actions/cache@v2
      with:
        path: plantuml.jar
        key: ${{ runner.os }}-${{ hashFiles('plantuml.jar') }}
    - run: wget -N --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
    - name: Get changed UML files
      id: puml-files
      run: git diff-tree -r --no-commit-id --name-status HEAD | awk --file ./.github/files/git_file_changes.awk
    - name: PlantUML Opts
      id: puml-opts
      run: |
        OPTS="-tsvg -I.config/plantuml/theme.puml -o .svg/mode -verbose"
        echo "::set-output name=light::$(echo $OPTS | sed -r 's/theme|mode/light-&/g')"
        echo "::set-output name=dark::$(echo $OPTS | sed -r 's/theme|mode/dark-&/g')"
    - run: java -jar plantuml.jar -version
    - name: Light Files Generate Changed
      run: java -jar plantuml.jar ${{ steps.puml-opts.outputs.light }} ${{ steps.puml-files.outputs.gen-files }}
      if: steps.changed.outputs.files != ''
    - name: Dark Files Generate Changed
      run: java -jar plantuml.jar ${{ steps.puml-opts.outputs.dark }} ${{ steps.puml-files.outputs.gen-files }}
      if: steps.changed.outputs.files != ''
    - name: Light Files Generate All
      run: java -jar plantuml.jar ${{ steps.puml-opts.outputs.light }} '**/*.puml'
      if: steps.changed.outputs.files == ''
    - name: Dark Files Generate All
      run: java -jar plantuml.jar ${{ steps.puml-opts.outputs.dark }} '**/*.puml'
      if: steps.changed.outputs.files == ''
    - uses: EndBug/add-and-commit@v7
      with:
        message: Generate SVG images for PlantUML diagrams
        add: ${{ steps.puml-files.outputs.gen-files }}
        remove: ${{ steps.puml-files.outputs.del-files }}
